### PR TITLE
Fix C printer output of array types in typedefs

### PR DESCRIPTION
**Pull request by dirx**
#11 - WIP

Added typedef array to test case.

### CODE REVIEW

**Comment by dirx** [comment]
@ircmaxell why are non function typedefs handled differently here? 

https://github.com/ircmaxell/php-c-parser/blob/d54308760986ebed81f0afe0ee9cb24f9641562f/lib/Printer/C.php#L53-L58

**Comment by ircmaxell** [comment]
Honestly, I don't remember. That code always gave me lots of problems conceptually for some reason (it's re-used in a few parts), and I am not sure why any of it is how it is. I am sure that I ran into a situation that this appeared to solve, but apparently not...

**Comment by dirx** [comment]
@ircmaxell Maybe appending names to functions did not work...

I dropped special handling & isFunction (might be a bc in case someone extended the C printer). 
But: this forces * to the right side. Do you have any preference here?

I did a quick run against (a cleaned up) rdkafka.h (mhhh ... no arrays here) and uuid.h. Looks good. Running against llvm would be helpful.

**Comment by ircmaxell** [comment]
> might be a bc in case someone extended the C printer

To my knowledge nobody is other than FFIMe, but can ship a major version bump if that's a big deal (I doubt it).

>  But: this forces * to the right side. Do you have any preference here?

It's less about preference and more about the meaning of the construct. Doesn't the position change the meaning of the declaration?

**Comment by dirx** [comment]
> It's less about preference and more about the meaning of the construct. Doesn't the position change the meaning of the declaration?

Right. I missed _the space_. I meant the right side of _the space_: 

- `int *bar` > before: `int * bar`
- `int *foo(void *baz)` > before: `int * foo(void *baz)`

Parentheses and arrays seem also quirky:

- `int (*waldo)[5]` gives `(int *waldo)[5]` which gives errors on reparsing

Will take a look at this.

**Comment by ircmaxell** [comment]
Ah, as far as space, I don't really have a preference. So happy to accept whatever :)

**Comment by dirx** [comment]
This example helped a lot with arrays and paranthesis: 

* `typedef char *(*(**hairy[][8])())[];`

See http://unixwiz.net/techtips/reading-cdecl.html.

@ircmaxell could you please take if this PR works for you.

**Comment by dirx** [comment]
This also fixes the "function type issue" mentioned in #2.

**Comment by ircmaxell** [comment]
Are you good with this as is? If so, I'm happy to merge.

**Comment by dirx** [comment]
Stumbled over the minor void trailing space issue and fixed it.

I successfully tested binding rdkafka, snappy, uuid, portalaudio and ffi with the c printer output. 
So, I am good with this.

**Comment by ircmaxell** [comment]
Awesome, Thanks!!!

**Pull request merged**
